LucieChevalier/winemeup

- .gitignore
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/initializers/devise.rb
- Ajout du fichier .env à Gitignore
- Ajout de la clé Cloudinary au fichier .env
- Ajout de la gem Cloudinary au Gemfile
> Cloudinary setup

- app/models/booking.rb
- app/models/bottle.rb
- app/models/event.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20220830110735_add_name_address_level_to_users.rb
- db/schema.rb
Models validations done + associations
> Validations

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Hello tout le monde: 
Demande de validation avant merge. 
J'ai travaille sur:
1. Info landing
2. Enleve la navbar sur sign in/up and root
> Infolanding

- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/index.html.erb
- config/routes.rb
- db/migrate/20220830125125_remove_price_range_from_events.rb
- db/migrate/20220830125305_add_min_and_max_price_to_events.rb
- db/schema.rb
- test/controllers/events_controller_test.rb
- Création de la route GET /events
- Création de l'events controller avec une méthode index
- Modification du schéma de DB (suppression de price_range, remplacé par deux colonnes min_price et max_price)
- Exception ajoutée sur le controller : pas besoin de se connecter pour accéder à l'index
- Création de la view index avec code ERB pour itération sur les événements (pas encore de style ni de mise en page)
- Validation des catégories (12 régions viticoles) dans le modèle event
> Created event controller + index view

- app/controllers/events_controller.rb
- app/views/events/show.html.erb
Creation de la methode show dans le controller 
Creation de la view avec strict minimum details
> Event show

- app/controllers/host/events_controller.rb
- app/models/event.rb
- app/views/host/events/create.html.erb
- app/views/host/events/new.html.erb
- config/routes.rb
- test/controllers/host/events_controller_test.rb
- Création du controller host/events
- Création de la page pour créer un événement (formulaire simple_form)
> First draft - As a host I can create an event

- app/views/pages/home.html.erb
For your review:
J'ai juste rajoute les liens vers les differentes pages correspondantes
> rajouter les liens vers les differentes pages correspondantes

- config/routes.rb
Création des routes principales (MUST HAVE), je suis pas sûre pour les autres mais on verra le moment venu
Création d'une route pour les composants (/components)
> Created main routes

- app/controllers/dashboards_controller.rb
- app/models/dashboard.rb
- app/models/event.rb
- app/models/user.rb
- app/views/dashboards/dashboard.html.erb
- db/migrate/20220831150934_create_dashboards.rb
- db/migrate/20220831152222_add_reference_to_dashboard.rb
- db/schema.rb
- test/controllers/dashboards_controller_test.rb
- test/models/dashboard_test.rb
- Créé un model et controller DASHBOARD
- Avec une view DASHBOARD
- J'ai été tripatouiller les models USER EVENT et DASHBOARD (en annotant mon code donc on pourra virer si besoin)
> Encore un gros fourre tout

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/javascript/controllers/edit_controller.js
- app/javascript/controllers/index.js
- app/models/event.rb
- app/views/devise/registrations/new.html.erb
- app/views/events/show.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20220831194430_split_address_users.rb
- db/schema.rb
- db/seeds.rb
Update profile done:
1. Migration de deux colums (city and postal code) into table: users
2. Split the addresses into three categories into the seeds (address = street, postal_code, city)
3. Add a link to icon to edit/update user profile
4. Method Update done
5. Profile info + edit form done with auto prefill
> Update profile done

- app/assets/stylesheets/components/_card-dashboard-2.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/dashboards/dashboard.html.erb
- db/seeds.rb
Ajout d'images aux seeds
Début d'ébauche de carte d'événement pour le dashboard
> seeds and card dashboard 2 draft

- app/assets/stylesheets/components/_card-dashboard-1.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/dashboards/dashboard.html.erb
- app/views/pages/components.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20220901104452_add_time_to_event.rb
- db/schema.rb
- db/seeds.rb
- Corrigé la config de Cloudinary
- Ajouté des avatars aux users dans les seeds (image pikachu)
- Ajouté une colonne TIME à la table EVENT
- Et création de la petite carte avec le nom de l'utilisateur et son avatar en haut du dashboard
> Card - Profil de l'utilisateur en haut du dashboard avec l'avatar

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_components.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/pages/components.html.erb
Enfin, tous les boutons rouges et blancs !
> boutons rouges et blancs

- app/assets/stylesheets/components/_card-dashboard-2.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/dashboards_controller.rb
- app/views/dashboards/dashboard.html.erb
- db/seeds.rb
+ refait les seeds (date et heure), changé quelques host et guests, etc.
> à peu près fini les petites cartes du dashboard

- app/assets/stylesheets/components/_card-dashboard-1.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_toggle-btn.scss
- app/views/dashboards/dashboard.html.erb
Ajout bouton toggle sur dashboard
Ajout du profil nesté sur le dashboard
Le passage de l'un à l'autre se fait via JS (à voir si on modifie)
Reste à mettre en page le profil et faire une page EDIT si besoin
> added toggle button on dashboard

- app/views/events/show.html.erb
- config/routes.rb
Formulaire ajouté à la show de l'event pour participer à cet event
##Problème : le formulaire ne disparait pas une fois qu'on est inscrit, du coup on peut s'inscrire autant de fois qu'on veut
> Added a form to join the event

- app/assets/stylesheets/components/_card-show.scss
- app/assets/stylesheets/components/_forms.scss
- app/controllers/events_controller.rb
- app/javascript/controllers/edit_controller.js
- app/javascript/controllers/search_events_controller.js
- app/views/events/_event_info.html.erb
- app/views/events/_search.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
Adding stimulus to display or hide button
> Stimulus on participate button

- app/views/dashboards/dashboard.html.erb
Les photos du dashboard sont cliquables
> Added clickable pictures on dashboard

- app/javascript/controllers/chatroom_subscription_controller.js
> Fix JS function

- app/views/events/show.html.erb
Le style de la show a un peu changé
> Changed the show
